baseURL = "https://fannyvieira.github.io/portfolio"
publishDir = "docs"
languageCode = "en-us"
title = "Fanny's Portfolio"
theme = "sam"

[[params.mainMenu]]
    link = "https://fannyvieira.github.io/blog/about"
    text = "call me fanny"

[[params.mainMenu]]
    link = "https://fannyvieira.github.io/blog/music"
    text = "sounds good"

[[params.mainMenu]]
    link = "https://fannyvieira.github.io/blog/gallery"
    text = "random save pictures"
