baseURL = "https://fannyvieira.github.io/portfolio"
publishDir = "docs"
languageCode = "en-us"
title = "Fanny's Portfolio"
theme = "sam"

[[params.mainMenu]]
    link = "https://fannyvieira.github.io/portfolio/about/"
    text = "call me funny"

[[params.mainMenu]]
    link = "https://fannyvieira.github.io/portfolio/music/"
    text = "sounds good"

[[params.mainMenu]]
    link = "https://fannyvieira.github.io/portfolio/gallery"
    text = "random save pictures"